### PR TITLE
Implement GET request

### PR DESCRIPTION
**Pull request by gilafonso**
This PR is to add the GET request for the sequences present in the uniprot database (fasta format). Also, minor changes to the input text and labels were made.

### CODE REVIEW

**Comment by smoretti** [comment]
Currently when I use the `public/` folder of the **ga/parsers** branch the fetching with the URL does not work, and the updated CSS rules are not there.

Maybe you did not push your public/ folder?

**Comment by gilafonso** [comment]
I just did the build with --release. Please check if everything is ok.

**Review by smoretti — CHANGES_REQUESTED** [review]
Everything works fine now.

Just replace the "Consolas" font-family by something else because it is not monospaced (at least on my Mac). "Courier" or "Courier new" are more widespread and monospaced.

**Review by smoretti — APPROVED** [review]
Great

**Pull request merged**
